### ISSUE TITLE
Assign-pids should also assign bendo identifiers

### ISSUE THREAD

**Issue by dbrower** [ndlib/rof#11]
This will be a third step, after assigning pids and resolving labels.

The algorithm is:

1. If an rof object has a value for the key `bendo-item`, it is left alone.
1. If an object does not have a value for `bendo-item`, it is given the same value as the value of `bendo-item` for the rof object just before it.
1. If there is no object before this one in the rof file, the value for its `bendo-item` is the object's pid with the namespace stripped out (e.g. `xyz:12345` becomes `12345`).

**Comment by msuhovec** [comment]
I'm assuming that this applies only for objects with a bendo-item ket: so in step two above, the key bendo-item exists for that object, but is set to nil.
