### ISSUE TITLE
Project 17 - Collections Batch Ingest

### ISSUE THREAD

**Issue by jeremyf** [ndlib/rof#23]
See specifications for [Technical Aspects of Collection Creation (Project 17)](https://docs.google.com/document/d/1ZjJz0tyEUsxpYo0oXsvb4lcoscFZ2qAsM2iJLdBvUyc/edit)

Work should be merged into the [project_17 branch](https://github.com/ndlib/rof/tree/project_17) as there is a coordination of services that needs to occur. If changes are made to ndlib/curatend-batch, use the [project_17 branch](https://github.com/ndlib/curatend-batch/tree/project_17) for that as well.

- [ ] Adjust usage of [ROF::Ingesters::RelsExtIngester](https://github.com/ndlib/rof/blob/master/lib/rof/ingesters/rels_ext_ingester.rb) to handle collections by adding entries analogue to the following (`<fedora-relations-model:isMemberOfCollection rdf:resource='info:fedora/und:pr76f190g2d'/>`)
- [ ] Account for how we may no longer need to leverage [batch's submit-collections](https://github.com/ndlib/curatend-batch/blob/master/tasks/submit-collections) but can instead add the collection directly to the object in the [items of the ROF document](https://github.com/ndlib/rof/blob/master/lib/rof/ingest.rb#L47-L63)

## Note

As a process rule, before an item can be added to a collection, the collection must already exist. There are features in curatend-batch that allow PID placeholders. That is something our processes should not allow; Enforcement will be by hand at this point.

**Comment by ruthtillman** [comment]
See https://docs.google.com/document/d/1ZjJz0tyEUsxpYo0oXsvb4lcoscFZ2qAsM2iJLdBvUyc/edit#heading=h.db6zd12j0581 for afmodel information.
