### ISSUE TITLE
enhance ingest to deal with collection image files

### ISSUE THREAD

**Issue by msuhovec** [ndlib/rof#25]
If an object to be ingested is type fobject, af-model Collection, and  contains the following attributes:

 {
    "content-file": "collection.png",
    "content-meta": {
      "mime-type": "image/png"
    },
    "thumbnail-file": "collection-thumb.png",
    "thumbnail-meta": {
      "mime-type": "image/png"
    },

encode its landing page and thumbnail images - I don't know yet whether this goes inline in the object, or as a datastream

**Comment by dbrower** [comment]
this will probably depend on how the new-style collections are implemented. @jeremyf

**Comment by jeremyf** [comment]
I'm planning on using the same thumbnail and content data structures as the existing collections.
