### ISSUE TITLE
ROF RelsExtRefContext needs isMemberOfCollection

### ISSUE THREAD

**Issue by msuhovec** [ndlib/rof#31]
the ROF fedora_to_rof task is failing to produce a valid JSON-LD representation of the RELS-EXT datastream  for fedora objects that are members of collection because it is missing context for isMemberOfCollection. It needs something like

 "isMemberOfCollection" => {"@type" => "@id"},

(I don't know if it maps to a proper fedora or hydra object)

**Comment by dbrower** [comment]
This makes sense; the `isMemberOfCollection` relation was added after I did the initial fedora to rof work.

**Comment by msuhovec** [comment]
I`m fixing another bug against this issue: in <datastream>-meta, the 'URL' is not being populate because ds.profile['TYPE'] is being looked for, instead of ds.profile['dsControlGroup'].
