### ISSUE TITLE
Extend ROF to handle "R" datastreams

### ISSUE THREAD

**Issue by dbrower** [ndlib/rof#7]
Need a way to say a datastream should be of type "R", and to give a URL (as well as mime-type, etc)

**Comment by dbrower** [comment]
Thinking something using the already existing `-meta` annotation. A field for URL could be added, which means save the datastream as type "E" using the given URL as the location. For example:

    {
        "content-meta" {
            "URL": "bendo:/item/123456/file.txt",
            "mime-type": "text/plain"
        }
    }

This means, as a special case, the ROF tool will need to resolve the `bendo:` scheme into a resolvable URL when this is put into fedora.

**Comment by dbrower** [comment]
If the datastream is already existing as a non-"E" type, the rof uploading tool will exit with an error. ("The datastream XXXX already exists and is not of type 'E'")

**Comment by msuhovec** [comment]
I think that this is done.

**Comment by dbrower** [comment]
Finished with PR #9.
